### ISSUE TITLE
Search repositories by multiple topics

### ISSUE THREAD

**Issue by AttackOnMorty** [AttackOnMorty/github-ranking#53]
**Is your feature request related to a problem? Please describe.**
I am unable to search repositories with multiple topics, e.g. React (Framework) and ChatGPT (Technology).

**Describe the solution you'd like**
Change single selector to multiple selector

**Additional context**
<img width="1380" alt="image" src="https://github.com/AttackOnMorty/github-ranking/assets/37203901/2be9b85e-ad88-4ba9-81eb-851a08f8693a">
**Figure: Single selector for topic**

**Comment by VINAAAYYY** [comment]
Hi, I want to contribute to this issue. I need some help with the flow.

**Comment by AttackOnMorty** [comment]
> Hi, I want to contribute to this issue. I need some help with the flow.

Hey @VINAAAYYY 👋,

For topic search flow:
1. Once you enter something in the topic input, it will trigger [TopicInput.handleSearch](https://github.com/AttackOnMorty/github-ranking/blob/1aac010ef7ed0293cd82e96b84c5f6a00b0d0890/src/components/TopicInput.tsx#L49) (Call GitHub API to get topics)
2. After you select a topic, it will trigger [TopicInput.handleChange](https://github.com/AttackOnMorty/github-ranking/blob/1aac010ef7ed0293cd82e96b84c5f6a00b0d0890/src/components/TopicInput.tsx#L57) (Set topic). Notice, setValue inside [TopicInput.handleChange](https://github.com/AttackOnMorty/github-ranking/blob/1aac010ef7ed0293cd82e96b84c5f6a00b0d0890/src/components/TopicInput.tsx#L57) is actually setTopic in Repositories component. See [here](https://github.com/AttackOnMorty/github-ranking/blob/1aac010ef7ed0293cd82e96b84c5f6a00b0d0890/src/components/Repositories.tsx#L112).
4. Since the topic changed, it will trigger the [Repositories.useEffect](https://github.com/AttackOnMorty/github-ranking/blob/1aac010ef7ed0293cd82e96b84c5f6a00b0d0890/src/components/Repositories.tsx#L34) (Fetch the repos with the changed topic)

Some tips for you:
- Check [Select](https://ant.design/components/select#select-demo-select-users) from Antd to see how we can change the existing single selector to a multiple selector.
- Check [GitHub API](https://docs.github.com/en/search-github/searching-on-github/searching-for-repositories#search-by-topic) to see how can we call API with multiple topics.

Please let me know if you have any questions 😊

**Comment by VINAAAYYY** [comment]
Hi @AttackOnMorty, I've created a PR for this issue. Please look into it.
Please refer: https://github.com/AttackOnMorty/github-ranking/pull/59

**Comment by AttackOnMorty** [comment]
✅ Done in https://github.com/AttackOnMorty/github-ranking/commit/d55ca6a527d5e7d88adcddebe5c141a2b296e283
